### ISSUE TITLE
Module `greenlet` needs to be added in the dependency list

### ISSUE THREAD

**Issue by sdglitched** [fedora-infra/webhook-to-fedora-messaging#106]
Module `greenlet` needs to be added in the dependency list

Faced below `traceback` when trying to initialize the database `w2fm --conf config setup`

```shell
Traceback (most recent call last):
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib/python3.13/site-packages/sqlalchemy_helpers/aio.py", line 170, in sync
    current_rev = await self.get_current_revision(session)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib/python3.13/site-packages/sqlalchemy_helpers/aio.py", line 110, in get_current_revision
    result = await session.execute(alembic_context._version.select())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib64/python3.13/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
                   ~~~~~~~~~~~~~~^
        self.sync_session.execute,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        **kw,
        ^^^^^
    )
    ^
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib64/python3.13/site-packages/sqlalchemy/util/concurrency.py", line 99, in greenlet_spawn
    _not_implemented()
    ~~~~~~~~~~~~~~~~^^
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib64/python3.13/site-packages/sqlalchemy/util/concurrency.py", line 79, in _not_implemented
    raise ValueError(
    ...<4 lines>...
    )
ValueError: the greenlet library is required to use this function. No module named 'greenlet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/bin/w2fm", line 6, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/sdglitched/webhook-to-fedora-messaging/webhook_to_fedora_messaging/cli.py", line 39, in setup
    result = run(setup_database())
  File "/usr/lib64/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/lib64/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib64/python3.13/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/sdglitched/webhook-to-fedora-messaging/webhook_to_fedora_messaging/database.py", line 40, in setup_database
    return await db.sync()
           ^^^^^^^^^^^^^^^
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib/python3.13/site-packages/sqlalchemy_helpers/aio.py", line 169, in sync
    async with self.Session() as session:
               ~~~~~~~~~~~~^^
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib64/python3.13/site-packages/sqlalchemy/ext/asyncio/session.py", line 1080, in __aexit__
    await asyncio.shield(task)
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib64/python3.13/site-packages/sqlalchemy/ext/asyncio/session.py", line 1025, in close
    await greenlet_spawn(self.sync_session.close)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib64/python3.13/site-packages/sqlalchemy/util/concurrency.py", line 99, in greenlet_spawn
    _not_implemented()
    ~~~~~~~~~~~~~~~~^^
  File "/home/sdglitched/webhook-to-fedora-messaging/venv/lib64/python3.13/site-packages/sqlalchemy/util/concurrency.py", line 79, in _not_implemented
    raise ValueError(
    ...<4 lines>...
    )
ValueError: the greenlet library is required to use this function. No module named 'greenlet'
```

**Comment by gridhead** [comment]
See https://github.com/fedora-infra/webhook-to-fedora-messaging/pull/107#issuecomment-2833248215.
