### ISSUE TITLE
Issue while setting up and running the project locally

### ISSUE THREAD

**Issue by sdglitched** [fedora-infra/webhook-to-fedora-messaging#109]
Found couple of more issues while trying to setup and run the project locally

1. While installing the dependencies with poetry monitored below traceback
```shell
  - Installing gssapi (1.9.0): Failed
    
  ChefBuildError
  
  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
    
  /bin/sh: line 1: krb5-config: command not found
  Traceback (most recent call last):
    File "/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
      ~~~~^^
    File "/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/tmpoa6ahu2a/.venv/lib/python3.13/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmpoa6ahu2a/.venv/lib/python3.13/site-packages/setuptools/build_meta.py", line 303, in _get_build_requires
      self.run_setup()
      ~~~~~~~~~~~~~~^^
    File "/tmp/tmpoa6ahu2a/.venv/lib/python3.13/site-packages/setuptools/build_meta.py", line 319, in run_setup
      exec(code, locals())
      ~~~~^^^^^^^^^^^^^^^^
    File "<string>", line 109, in <module>
    File "<string>", line 22, in get_output
    File "/usr/lib64/python3.13/subprocess.py", line 472, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 **kwargs).stdout
                 ^^^^^^^^^
    File "/usr/lib64/python3.13/subprocess.py", line 577, in run
      raise CalledProcessError(retcode, process.args,
                               output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127.
  

  at /usr/lib/python3.13/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with gssapi (1.9.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "gssapi (==1.9.0)"'.
```
It seems `krb5-devel` needs to be installed as pre-requisite 

2. While trying to run the project found a typo in `README.md` (missing `\`)
![image](https://github.com/user-attachments/assets/9f103738-9b8f-48d3-bca4-57720d790a6f)

3. After fixing the above two issues locally and trying to hit the endpoint `/api /v1 /users /search /{username}` api failed with code=500 as no table `users` was present in database
![image](https://github.com/user-attachments/assets/13471ed0-3807-4feb-87dd-45e743750802)
![image](https://github.com/user-attachments/assets/2581b889-293a-4923-8813-e43cc526324b)
Also, a new database file was created `webhook-to-fedora-messaging.db`
![image](https://github.com/user-attachments/assets/07ff6726-c48d-4841-8539-f8b3dc4152b7)
It seems W2FM_CONFIG (in my case: /home/sdglitched/webhook-to-fedora-messaging/config) needs to be exported for correct functioning

**Comment by gridhead** [comment]
Fixed by #110. Thanks @sdglitched!
