### ISSUE TITLE
Improper initialisation of SEND_FILE_MAX_AGE_DEFAULT parameter in conf.toml

### ISSUE THREAD

**Issue by brngylni** [fedora-infra/webhook-to-fedora-messaging#45]
We had removed some parameters from  `conf.toml` since they were problematic. Just realised the SEND_FILE_MAX_AGE_DEFAULT parameter is also initialised with an empty string which makes it fail when trying to initialise Swagger and throws the following exception: 

```
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/werkzeug/utils.py", line 508, in send_file
    if max_age > 0:
       ^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'
[W2FM] [2024-07-30 12:26:29 +0300] - werkzeug - INFO - 127.0.0.1 - - [30/Jul/2024 12:26:29] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 500 -
[2024-07-30 12:26:30,150] ERROR in app: Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask/blueprints.py", line 100, in send_static_file
    return send_from_directory(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask/helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/werkzeug/utils.py", line 577, in send_from_directory
    return send_file(path_str, environ, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/werkzeug/utils.py", line 508, in send_file
    if max_age > 0:
       ^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'
[W2FM] [2024-07-30 12:26:30 +0300] - webhook_to_fedora_messaging - ERROR - Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask/blueprints.py", line 100, in send_static_file
    return send_from_directory(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/flask/helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/werkzeug/utils.py", line 577, in send_from_directory
    return send_file(path_str, environ, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghost/repo/repo/stage/webhook-to-fedora-messaging/venv/lib64/python3.12/site-packages/werkzeug/utils.py", line 508, in send_file
    if max_age > 0:
       ^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'

```

So I can create a pull request if we all agree upon that it should be removed or initialised with proper value which is an integer in this case.

 @gridhead  @abompard

**Comment by abompard** [comment]
Yep, please send a PR.

**Comment by brngylni** [comment]
> Yep, please send a PR.

Should I remove it or set to another optimal value?

**Comment by abompard** [comment]
Let's remove it, it's documented in the Flask config if anyone wants to change it.

**Comment by gridhead** [comment]
Closing this as this is no longer needed with the most recent port done to FastAPI.
